name: CI - Build & Push Docker (CD Ready)

# This workflow builds and can push Docker image
# Uncomment push step when ready for CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build project with Maven
      run: |
        cd assignment_5
        mvn clean package
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        cd assignment_5
        docker build . --file Dockerfile --tag assignment_5:latest
    
    - name: Upload JAR artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: jar-file
        path: assignment_5/target/*.jar
        retention-days: 7
