name: CI - Build & Push Docker (CD Ready)

# This workflow builds and can push Docker image
# Uncomment push step when ready for CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build project
      run: mvn clean package
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: assignment_5:latest
        file: ./Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    # Uncomment below when ready for CD with Docker Hub
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    # 
    # - name: Push Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: true
    #     tags: |
    #       ${{ secrets.DOCKER_USERNAME }}/assignment_5:latest
    #       ${{ secrets.DOCKER_USERNAME }}/assignment_5:${{ github.sha }}
    #     file: ./Dockerfile
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
    
    - name: Upload JAR artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: jar-file
        path: target/*.jar
        retention-days: 7
