apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-management-data
  namespace: assignment-5
  labels:
    app: course-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: docker-desktop
