apiVersion: v1
kind: Service
metadata:
  name: course-management-service
  namespace: assignment-5
  labels:
    app: course-management
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: course-management
