apiVersion: v1
kind: Service
metadata:
  name: spring-course-app-service
  namespace: course-app
  labels:
    app: spring-course-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-course-app
